server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/heeven/development/spring-boot-kotlin-todo-sample/configurationserver/src/main/resources/config/todo-service